import requests,re,os
import numpy as np
from PIL import Image
url = "https://www.iqiyi.com/manhua/reader/dwlgg5bnp1_1j4emmb00x5.html"
ua = {'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0'}
reg1 = requests.get(url,headers=ua)
reg1.encoding = reg1.apparent_encoding
reg = reg1.text
if os.path.exists("f:\\漫画") == False:
    os.mkdir("f:\\漫画")
path1 = "哈哈哈"
iy = 0
ret = re.findall(r'img src="(.*?)"',reg)
for i in  ret:
    print(i)
data_original = re.findall(r'img data-original="(.*?)"',reg)
for i in  data_original:
    if iy == iy :
        iy+=1
        mi = str(iy)+".jpg"
        print(mi)
        print(iy)
        name1 = requests.get(i)
        with open("f:\\漫画" + "/" + mi, "wb") as f:
            f.write(name1.content)
    print(i)
"""
iy=0
open = os.listdir("f:\\漫画")
open.sort(key=lambda x:int(x[:-4]))
print(open)
for iopth in open:
    if iy == iy:
        iy+=1
        #ming = str(iy)+".jpg"
        img = Image.open("f:\\漫画\\%s"%"1.jpg")
        img1 = Image.open("f:\\漫画\\2.jpg")
        img2 = Image.open("f:\\漫画\\3.jpg")
        im,im1,im2 = np.array(img),np.array(img1),np.array(img2)
        i1 = np.concatenate((im, im1, im2), axis=0)
        img1.save('F:\\漫画\\拼接\\拼接1.jpg')
        img = Image.open("f:\\漫画\\4.jpg")
        img1 = Image.open("f:\\漫画\\5.jpg")
        img2 = Image.open("f:\\漫画\\6.jpg")
        im, im1, im2 = np.array(img), np.array(img1), np.array(img2)
        i2 = np.concatenate((im, im1, im2), axis=0)
        img1.save('F:\\漫画\\拼接\\拼接2.jpg')
        img = Image.open("f:\\漫画\\7.jpg")
        img1 = Image.open("f:\\漫画\\8.jpg")
        img2 = Image.open("f:\\漫画\\9.jpg")
        im, im1, im2 = np.array(img), np.array(img1), np.array(img2)
        i3 = np.concatenate((im, im1, im2), axis=0)
        img1.save('拼接3.jpg')
        img = Image.open("f:\\漫画\\10.jpg")
        img1 = Image.open("f:\\漫画\\11.jpg")
        img2 = Image.open("f:\\漫画\\12.jpg")
        im, im1, im2 = np.array(img), np.array(img1), np.array(img2)
        i4 = np.concatenate((im, im1, im2), axis=0)
        img1.save('拼接4.jpg')
        img = Image.open("f:\\漫画\\13.jpg")
        img1 = Image.open("f:\\漫画\\14.jpg")
        img2 = Image.open("f:\\漫画\\15.jpg")
        im, im1, im2 = np.array(img), np.array(img1), np.array(img2)
        i5 = np.concatenate((im, im1, im2), axis=0)
        img1.save('拼接5.jpg')
        img = Image.open("f:\\漫画\\16.jpg")
        img1 = Image.open("f:\\漫画\\17.jpg")
        img2 = Image.open("f:\\漫画\\18.jpg")
        im, im1, im2 = np.array(img), np.array(img1), np.array(img2)
        i6 = np.concatenate((im, im1, im2), axis=0)
        img1.save('拼接6.jpg')
        img = Image.open("f:\\漫画\\19.jpg")
        img1 = Image.open("f:\\漫画\\20.jpg")
        img2 = Image.open("f:\\漫画\\21.jpg")
        im, im1, im2 = np.array(img), np.array(img1), np.array(img2)
        i7 = np.concatenate((im, im1, im2), axis=0)
        img1.save('拼接7.jpg')
        img = Image.open("f:\\漫画\\22.jpg")
        img1 = Image.open("f:\\漫画\\23.jpg")
        img2 = Image.open("f:\\漫画\\24.jpg")
        im, im1, im2 = np.array(img), np.array(img1), np.array(img2)
        i8 = np.concatenate((im, im1, im2), axis=0)
        img1.save('拼接8.jpg')
        img = Image.open("f:\\漫画\\25.jpg")
        img1 = Image.open("f:\\漫画\\26.jpg")
        img2 = Image.open("f:\\漫画\\27.jpg")
        im, im1, im2 = np.array(img), np.array(img1), np.array(img2)
        i9 = np.concatenate((im, im1, im2), axis=0)
        img1.save('拼接9.jpg')
        img = Image.open("f:\\漫画\\28.jpg")
        img1 = Image.open("f:\\漫画\\29.jpg")
        img2 = Image.open("f:\\漫画\\30.jpg")
        im, im1, im2 = np.array(img), np.array(img1), np.array(img2)
        i10 = np.concatenate((im, im1, im2), axis=0)
        img1.save('拼接10.jpg')
        img = Image.open("f:\\漫画\\31.jpg")
        img1 = Image.open("f:\\漫画\\32.jpg")
        img2 = Image.open("f:\\漫画\\33.jpg")
        im, im1, im2 = np.array(img), np.array(img1), np.array(img2)
        i11 = np.concatenate((im, im1, im2), axis=0)
        img1.save('拼接11.jpg')
        img = Image.open("f:\\漫画\\34.jpg")
        img1 = Image.open("f:\\漫画\\35.jpg")
        img2 = Image.open("f:\\漫画\\36.jpg")
        im, im1, im2 = np.array(img), np.array(img1), np.array(img2)
        i12 = np.concatenate((im, im1, im2), axis=0)
        img1.save('拼接12.jpg')
        img = Image.open("f:\\漫画\\37.jpg")
        img1 = Image.open("f:\\漫画\\38.jpg")
        img2 = Image.open("f:\\漫画\\39.jpg")
        im, im1, im2 = np.array(img), np.array(img1), np.array(img2)
        i13 = np.concatenate((im, im1, im2), axis=0)
        img1.save('拼接13.jpg')
        img = Image.open("f:\\漫画\\40.jpg")
        img1 = Image.open("f:\\漫画\\41.jpg")
        img2 = Image.open("f:\\漫画\\42.jpg")
        im, im1, im2 = np.array(img), np.array(img1), np.array(img2)
        i14 = np.concatenate((im, im1, im2), axis=0)
        img1.save('拼接14.jpg')
        img = Image.open("f:\\漫画\\43.jpg")
        img1 = Image.open("f:\\漫画\\44.jpg")
        img2 = Image.open("f:\\漫画\\45.jpg")
        im, im1, im2 = np.array(img), np.array(img1), np.array(img2)
        i15 = np.concatenate((im, im1, im2), axis=0)
        img1.save('拼接15.jpg')
        img = Image.open("f:\\漫画\\46.jpg")
        img1 = Image.open("f:\\漫画\\47.jpg")
        img2 = Image.open("f:\\漫画\\48.jpg")
        im, im1, im2 = np.array(img), np.array(img1), np.array(img2)
        i16 = np.concatenate((im, im1, im2), axis=0)
        img1.save('拼接16.jpg')
        img = Image.open("f:\\漫画\\49.jpg")
        img1 = Image.open("f:\\漫画\\50.jpg")
        img2 = Image.open("f:\\漫画\\51.jpg")
        im, im1, im2 = np.array(img), np.array(img1), np.array(img2)
        i17 = np.concatenate((im, im1, im2), axis=0)
        img1.save('拼接17.jpg')
        img = Image.open("f:\\漫画\\52.jpg")
        img1 = Image.open("f:\\漫画\\53.jpg")
        img3 = Image.open("f:\\漫画\\54.jpg")
        im, im1, im2 = np.array(img), np.array(img1), np.array(img2)
        i18 = np.concatenate((im, im1, im2), axis=0)
        img1.save('拼接18.jpg')
"""
